AllCops:
  TargetRubyVersion: 2.5
  TargetRailsVersion: 5.1

  CacheRootDirectory: /tmp
  AllowSymlinksInCacheRootDirectory: true

  Exclude:
    - 'apidoc/**/*'
    - 'bin/bundle'
    - 'bin/rails'
    - 'bin/rake'
    - 'bin/setup'
    - 'bin/spring'
    - 'bin/update'
    - 'db/schema.rb'
    - 'node_modules/**/*'
    - 'spec/dummy/**/*'
    - 'vendor/**/*'
    - 'repos/**/*'

Layout/AlignParameters:
  Enabled: false

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Metrics/BlockLength:
  Exclude:
    - 'app/graphql/**/*'
    - 'config/routes.rb'
    - 'config/environments/**/*'
    - 'config/initializers/devise.rb'
    - 'spec/**/*'
    - 'db/migrate/*'
    - '*.gemspec'

Metrics/LineLength:
  Exclude:
    - 'app/graphql/**/*_enum.rb'
    - 'config/initializers/devise.rb'
    - 'features/steps/**/*.rb'

Style/DoubleNegation:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/GlobalVars:
  Exclude:
    - 'features/steps/**/*.rb'
    - 'features/support/aruba.rb'
    - 'features/support/hooks.rb'

Style/NumericLiterals:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: ()
    '%i': '()'
    '%I': '()'
    '%r': '{}'
    '%w': '()'
    '%W': '()'

Style/SymbolArray:
  Exclude:
    - 'db/migrate/**'

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma
