Metrics/BlockLength:
  Exclude:
    - 'app/graphql/**/*'
    - 'config/routes.rb'
    - 'config/environments/**/*'
    - 'config/initializers/devise.rb'
    - 'spec/**/*'
    - 'db/migrate/*'
    - '*.gemspec'

Metrics/LineLength:
  Exclude:
    - 'app/graphql/**/*_enum.rb'
    - 'config/initializers/devise.rb'
    - 'features/steps/**/*.rb'

Layout/AlignParameters:
  Enabled: false

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/GlobalVars:
  Exclude:
    - 'features/steps/**/*.rb'
    - 'features/support/aruba.rb'
    - 'features/support/hooks.rb'

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: ()
    '%i': '()'
    '%I': '()'
    '%r': '{}'
    '%w': '()'
    '%W': '()'

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Style/DoubleNegation:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/SymbolArray:
  Exclude:
    - 'db/migrate/**'

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma
