sudo: required
dist: trusty

language: ruby

rvm:
  - 2.4.1
  - rbx-3.82

matrix:
  fast_finish: true
  allow_failures:
  - rvm: rbx-3.82

services:
  - postgresql

addons:
  postgresql: '9.6'

notifications:
  email: false

addons:
  apt:
    packages:
    - git-svn

before_script:
  - RAILS_ENV=test bundle exec rails db:recreate
  - RAILS_ENV=development bundle exec rails db:recreate:seed

script:
  - bundle exec rake
