sudo: required
dist: trusty

language: ruby

cache:
  bundler: true
  directories:
    - $HOME/system-test

rvm:
  - 2.4.2

services:
  - postgresql

notifications:
  email: false

addons:
  postgresql: '9.6'
  apt:
    packages:
    - git-svn

matrix:
  include:
    - env: WITH_SEEDS=1
      services:
        - rabbitmq
      before_install:
        - sudo rabbitmq-plugins enable rabbitmq_recent_history_exchange
      script:
        - bundle exec rails db:recreate:seed
    - env: WITH_RSPEC=1
      before_script:
        - RAILS_ENV=test bundle exec rails db:recreate
      script:
        - bundle exec rspec
    - env: WITH_SYSTEM_TEST=1 BUNDLE_GEMFILE=$HOME/system-test/Gemfile
      before_script:
        - |
          if [ -d $HOME/system-test/.git ]
          then
            pushd $HOME/system-test
            git pull
            popd
          else
            git clone --depth=1 https://github.com/ontohub/system-test.git $HOME/system-test
          fi
        - pushd $HOME/system-test
        - bundle install
        - popd
      script:
        - pushd $HOME/system-test
        - cucumber
        - popd
