sudo: required
dist: trusty

language: ruby

cache: bundler

rvm:
  - 2.4.2

services:
  - postgresql
  - rabbitmq

notifications:
  email: false

addons:
  postgresql: '9.6'
  apt:
    packages:
    - git-svn

matrix:
  include:
    - env: WITH_SEEDS=1
      script:
        - bundle exec rails db:recreate:seed
    - env: WITH_RSPEC=1
      before_script:
        - RAILS_ENV=test bundle exec rails db:recreate
      script:
        - bundle exec rspec

before_install:
  - sudo rabbitmq-plugins enable rabbitmq_recent_history_exchange
