sudo: required
dist: trusty

language: ruby

cache: bundler

rvm:
  - 2.4.2

services:
  - postgresql
  - rabbitmq

notifications:
  email: false

addons:
  postgresql: '9.6'
  apt:
    packages:
    - git-svn

matrix:
  include:
    - env: WITH_SEEDS=1
    - env: WITH_RSPEC=1

before_install:
  - sudo rabbitmq-plugins enable rabbitmq_recent_history_exchange

before_script:
  - if [ -n "$WITH_RSPEC" ]; then RAILS_ENV=test bundle exec rails db:recreate;   fi

script:
  - bundle exec rake
  - if [ -n "$WITH_SEEDS" ]; then bundle exec rails db:recreate:seed; fi
  - if [ -n "$WITH_RSPEC" ]; then bundle exec rspec; fi
