sudo: required
dist: trusty

language: ruby

cache:
  bundler: true
  directories:
    - $HOME/system-test

rvm:
  - 2.5.0

services:
  - postgresql

notifications:
  email: false

addons:
  postgresql: '9.6'
  apt:
    packages:
    - git-svn

matrix:
  fast_finish: true
  allow_failures:
    - env: JOB=system-test
  include:
    - env: JOB=seeds
      services:
        - rabbitmq
      before_install:
        # This is a workaround for a problem with a specific version of bundler
        # and rubygems
        - gem update --system
        - sudo rabbitmq-plugins enable rabbitmq_recent_history_exchange
      script:
        - bundle exec rails db:recreate:seed

    - env: JOB=rspec
      before_install:
        # This is a workaround for a problem with a specific version of bundler
        # and rubygems
        - gem update --system
      before_script:
        - RAILS_ENV=test bundle exec rails db:recreate
      script:
        - bundle exec rspec --format progress

    - env: JOB=system-test
      gemfile: $HOME/system-test/Gemfile
      services:
        - rabbitmq
      before_install:
        # This is a workaround for a problem with a specific version of bundler
        # and rubygems
        - gem update --system
        - sudo rabbitmq-plugins enable rabbitmq_recent_history_exchange
      install:
        - EMAJ_VERSION=2.1.0
        - curl -Lo /tmp/emaj.zip http://api.pgxn.org/dist/e-maj/$EMAJ_VERSION/e-maj-$EMAJ_VERSION.zip
        - EMAJ_TMPDIR=/tmp/emaj
        - unzip /tmp/emaj.zip -d $EMAJ_TMPDIR/
        - EMAJ_SQL_FILE=$EMAJ_TMPDIR/e-maj-$EMAJ_VERSION/sql/emaj--$EMAJ_VERSION.sql
        - EMAJ_CONTROL_FILE=$EMAJ_TMPDIR/e-maj-$EMAJ_VERSION/emaj.control
        - SHAREDIR=$(pg_config --sharedir)
        - sudo mkdir -p $SHAREDIR/extension/
        - sudo cp $EMAJ_SQL_FILE $EMAJ_CONTROL_FILE $SHAREDIR/extension/
      before_script:
        - |
          if [ -d $HOME/system-test/.git ]
          then
            pushd $HOME/system-test
            git pull
            popd
          else
            git clone --depth=1 https://github.com/ontohub/system-test.git $HOME/system-test
          fi
        - pushd $HOME/system-test
        - bundle install
        - popd
      script:
        - pushd $HOME/system-test
        - echo "Testing commit $TRAVIS_COMMIT"
        - ONTOHUB_BACKEND_VERSION=$TRAVIS_COMMIT cucumber
        - popd
