sudo: required
dist: trusty

language: ruby

rvm:
  - 2.4.1
  - rbx-3.73

services:
  - postgresql

addons:
  postgresql: '9.6'

notifications:
  email: false

before_script:
  - RAILS_ENV=test bin/rails db:recreate

script:
  - bundle exec rake
