sudo: required
dist: trusty

language: ruby

rvm:
  - 2.4.1
  - rbx-3.77

services:
  - postgresql

addons:
  postgresql: '9.6'

notifications:
  email: false

addons:
  apt:
    packages:
    - git-svn

before_script:
  - RAILS_ENV=test bin/rails db:recreate

script:
  - bundle exec rake
