sudo: required
dist: trusty

language: ruby

rvm:
  - 2.3.1

services:
  - postgresql

addons:
  postgresql: '9.4'

notifications:
  email: false

before_script:
  - RAILS_ENV=test bin/rails db:recreate

script:
  - bundle exec rake
