# frozen_string_literal: true

# rubocop:disable Metrics/LineLength

Types::MappingTypeEnum = GraphQL::EnumType.define do
  name 'MappingType'
  description 'Specifies the type of the Mapping (=link in the development graph)'

  value 'local_def', 'local definition link'
  value 'local_thm_open', 'open local theorem link'
  value 'local_thm_proved', 'proved local theorem link'
  value 'global_def', 'global definition link'
  value 'global_thm_open', 'open global theorem link'
  value 'global_thm_proved', 'proved global theorem link'
  value 'hiding_def', 'hiding defintion link'
  value 'free_def', 'free definition link'
  value 'cofree_def', 'cofree definition link'
  value 'np_free_def', 'free definition link generated by Maude'
  value 'minimize_def', 'minimization definition link'
  value 'hiding_open', 'open hiding theorem link'
  value 'hiding_proved', 'proved hiding theorem link'
  value 'free_open', 'open free theorem link'
  value 'cofree_open', 'open cofree theorem link'
  value 'np_free_open', 'open free theorem link generated by Maude'
  value 'minimize_open', 'open minimization theorem link'
  value 'free_proved', 'proved free theorem link'
  value 'cofree_proved', 'proved cofree theorem link'
  value 'np_free_proved', 'proved free theorem link generated by Maude'
  value 'minimize_proved', 'proved minimization theorem link'
end
