# frozen_string_literal: true

Types::VersionType = GraphQL::ObjectType.define do
  name 'Version'
  description 'Version of the running backend'

  field :full, !types.String do
    description 'Full version as generated by `git describe --long --tags`'
  end

  field :commit, !types.String do
    description 'Short git hash of the deployed version'
  end

  field :tag, !types.String do
    description 'Last published version'
  end

  field :commitsSinceTag, !types.Int do
    description 'Amount of commits since the last version bump'
    property :commits_since_tag
  end
end
