# frozen_string_literal: true

Types::VersionType = GraphQL::ObjectType.define do
  name 'Version'
  field :full,
        !types.String,
        'Full version as generated by `git describe --long --tags`'
  field :commit,
        !types.String,
        'Short git hash of the deployed version'
  field :tag,
        !types.String,
        'Last published version'
  field :commitsSinceTag, !types.Int do
    description 'Amount of commits since the last version bump'
    property :commits_since_tag
  end
end
