# The base URL for URL generation without trailing slash
server_url: 'http://localhost:3000'

jwt:
  expiration_hours: 24

# The data directory contains all the git repositories. A relative path is
# interpreted relative to the application root directory.
# This directory will be created if it does not exist.
data_directory: 'data'

git_shell:
  path: ../git-shell/bin/git-shell

rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest
  virtual_host: ontohub_development

sneakers:
  - classes: MailersWorker
    workers: 1
  - classes: ProcessCommitWorker
    workers: 1
  - classes: PostProcessHetsWorker
    workers: 1
  - classes: RepositoryPullingWorker
    workers: 1
  - classes: RepositoryCloningWorker
    workers: 1
